package dev.fmhj97.whatdoicookbackend.service;

import dev.fmhj97.whatdoicookbackend.dto.recipe.RecipeCreateDto;
import dev.fmhj97.whatdoicookbackend.dto.recipe.RecipeResponseDto;
import dev.fmhj97.whatdoicookbackend.dto.recipe.RecipeUpdateDto;
import dev.fmhj97.whatdoicookbackend.entity.Recipe;
import dev.fmhj97.whatdoicookbackend.entity.User;
import dev.fmhj97.whatdoicookbackend.entity.enums.FoodType;
import dev.fmhj97.whatdoicookbackend.entity.enums.Role;
import dev.fmhj97.whatdoicookbackend.entity.enums.Source;
import dev.fmhj97.whatdoicookbackend.exception.DuplicateResourceException;
import dev.fmhj97.whatdoicookbackend.exception.ForbiddenException;
import dev.fmhj97.whatdoicookbackend.exception.InvalidDataException;
import dev.fmhj97.whatdoicookbackend.exception.ResourceNotFoundException;
import dev.fmhj97.whatdoicookbackend.repository.RecipeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RecipeServiceTest {

    @Mock private RecipeRepository recipeRepository;

    @InjectMocks private RecipeService recipeService;

    private User owner;
    private User anotherUser;
    private Recipe recipe;

    @BeforeEach
    void setUp() {
        // Create two users to test ownership checks
        owner = new User("francisco", "francisco@test.com", "encoded", Role.USER);
        anotherUser = new User("other", "other@test.com", "encoded", Role.USER);

        // Use reflection to set IDs since they are generated by the DB
        setId(owner, 1L);
        setId(anotherUser, 2L);

        recipe = new Recipe("Paella", owner, "Classic Spanish dish", FoodType.RICE, Source.USER, 4, 30, 60);
        setId(recipe, 1L);
    }

    // Helper to set private IDs via reflection (since there's no setter for ID)
    private void setId(Object entity, Long id) {
        try {
            var field = entity.getClass().getDeclaredField("id");
            field.setAccessible(true);
            field.set(entity, id);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // --- getRecipeById() ---

    @Test
    void getRecipeById_ShouldReturnRecipe_WhenOwnerRequests() {
        // Arrange
        when(recipeRepository.findById(1L)).thenReturn(Optional.of(recipe));

        // Act
        RecipeResponseDto result = recipeService.getRecipeById(1L, owner);

        // Assert
        assertThat(result.title()).isEqualTo("Paella");
    }

    @Test
    void getRecipeById_ShouldThrowForbiddenException_WhenNotOwner() {
        // Arrange
        when(recipeRepository.findById(1L)).thenReturn(Optional.of(recipe));

        // Assert + Act — anotherUser does not own this recipe
        assertThatThrownBy(() -> recipeService.getRecipeById(1L, anotherUser))
                .isInstanceOf(ForbiddenException.class);
    }

    @Test
    void getRecipeById_ShouldThrowResourceNotFoundException_WhenNotExists() {
        // Arrange
        when(recipeRepository.findById(99L)).thenReturn(Optional.empty());

        // Assert + Act
        assertThatThrownBy(() -> recipeService.getRecipeById(99L, owner))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("99");
    }

    // --- getMyRecipes() ---

    @Test
    void getMyRecipes_ShouldReturnAllRecipes_WhenNoFilters() {
        // Arrange
        when(recipeRepository.findByOwnerId(1L)).thenReturn(List.of(recipe));

        // Act
        List<RecipeResponseDto> result = recipeService.getMyRecipes(owner, null, null);

        // Assert
        assertThat(result).hasSize(1);
        verify(recipeRepository).findByOwnerId(1L);
    }

    @Test
    void getMyRecipes_ShouldFilterByTitle_WhenTitleProvided() {
        // Arrange
        when(recipeRepository.findByOwnerIdAndTitleContainingIgnoreCase(1L, "Paella"))
                .thenReturn(List.of(recipe));

        // Act
        List<RecipeResponseDto> result = recipeService.getMyRecipes(owner, "Paella", null);

        // Assert
        assertThat(result).hasSize(1);
        verify(recipeRepository).findByOwnerIdAndTitleContainingIgnoreCase(1L, "Paella");
    }

    @Test
    void getMyRecipes_ShouldFilterByFoodType_WhenFoodTypeProvided() {
        // Arrange
        when(recipeRepository.findByOwnerIdAndFoodType(1L, FoodType.RICE))
                .thenReturn(List.of(recipe));

        // Act
        List<RecipeResponseDto> result = recipeService.getMyRecipes(owner, null, FoodType.RICE);

        // Assert
        assertThat(result).hasSize(1);
        verify(recipeRepository).findByOwnerIdAndFoodType(1L, FoodType.RICE);
    }

    @Test
    void getMyRecipes_ShouldFilterByBoth_WhenTitleAndFoodTypeProvided() {
        // Arrange
        when(recipeRepository.findByOwnerIdAndTitleContainingIgnoreCaseAndFoodType(1L, "Paella", FoodType.RICE))
                .thenReturn(List.of(recipe));

        // Act
        List<RecipeResponseDto> result = recipeService.getMyRecipes(owner, "Paella", FoodType.RICE);

        // Assert
        assertThat(result).hasSize(1);
        verify(recipeRepository).findByOwnerIdAndTitleContainingIgnoreCaseAndFoodType(1L, "Paella", FoodType.RICE);
    }

    // --- createRecipe() ---

    @Test
    void createRecipe_ShouldReturnCreatedRecipe_WhenValidData() {
        // Arrange
        RecipeCreateDto dto = new RecipeCreateDto("Tortilla", "Spanish omelette", FoodType.MEAT, 2, 10, 15);
        when(recipeRepository.existsByOwnerIdAndTitleIgnoreCase(1L, "Tortilla")).thenReturn(false);
        when(recipeRepository.save(any(Recipe.class))).thenReturn(recipe);

        // Act
        RecipeResponseDto result = recipeService.createRecipe(owner, dto);

        // Assert
        assertThat(result).isNotNull();
        verify(recipeRepository).save(any(Recipe.class));
    }

    @Test
    void createRecipe_ShouldThrowDuplicateResourceException_WhenTitleExists() {
        // Arrange
        RecipeCreateDto dto = new RecipeCreateDto("Paella", null, FoodType.RICE, null, null, null);
        when(recipeRepository.existsByOwnerIdAndTitleIgnoreCase(1L, "Paella")).thenReturn(true);

        // Assert + Act
        assertThatThrownBy(() -> recipeService.createRecipe(owner, dto))
                .isInstanceOf(DuplicateResourceException.class)
                .hasMessageContaining("Paella");

        verify(recipeRepository, never()).save(any());
    }

    // --- deleteRecipe() ---

    @Test
    void deleteRecipe_ShouldDelete_WhenOwnerRequests() {
        // Arrange
        when(recipeRepository.findById(1L)).thenReturn(Optional.of(recipe));

        // Act
        recipeService.deleteRecipe(owner, 1L);

        // Verify deleteById was called
        verify(recipeRepository).deleteById(1L);
    }

    @Test
    void deleteRecipe_ShouldThrowForbiddenException_WhenNotOwner() {
        // Arrange
        when(recipeRepository.findById(1L)).thenReturn(Optional.of(recipe));

        // Assert + Act
        assertThatThrownBy(() -> recipeService.deleteRecipe(anotherUser, 1L))
                .isInstanceOf(ForbiddenException.class);

        verify(recipeRepository, never()).deleteById(any());
    }

    // --- updateRecipe() ---

    @Test
    void updateRecipe_ShouldReturnUpdatedRecipe_WhenOwnerRequests() {
        // Arrange
        RecipeUpdateDto dto = new RecipeUpdateDto("Updated Paella", null, null, null, null, null);
        when(recipeRepository.findById(1L)).thenReturn(Optional.of(recipe));
        when(recipeRepository.existsByOwnerIdAndTitleIgnoreCase(1L, "Updated Paella")).thenReturn(false);
        when(recipeRepository.save(any(Recipe.class))).thenReturn(recipe);

        // Act
        RecipeResponseDto result = recipeService.updateRecipe(owner, 1L, dto);

        // Assert
        assertThat(result).isNotNull();
        verify(recipeRepository).save(any(Recipe.class));
    }

    @Test
    void updateRecipe_ShouldThrowForbiddenException_WhenNotOwner() {
        // Arrange
        RecipeUpdateDto dto = new RecipeUpdateDto("New Title", null, null, null, null, null);
        when(recipeRepository.findById(1L)).thenReturn(Optional.of(recipe));

        // Assert + Act
        assertThatThrownBy(() -> recipeService.updateRecipe(anotherUser, 1L, dto))
                .isInstanceOf(ForbiddenException.class);
    }

    // --- getRecipesByFilter() ---

    @Test
    void getRecipesByFilter_ShouldThrowInvalidDataException_WhenNoIngredients() {
        // Assert + Act — empty list should throw InvalidDataException
        assertThatThrownBy(() -> recipeService.getRecipesByFilter(owner, List.of(), null))
                .isInstanceOf(InvalidDataException.class);
    }

    @Test
    void getRecipesByFilter_ShouldReturnRecipes_WhenIngredientsProvided() {
        // Arrange
        when(recipeRepository.findByOwnerIdAndIngredientIds(1L, List.of(1L, 2L)))
                .thenReturn(List.of(recipe));

        // Act
        List<RecipeResponseDto> result = recipeService.getRecipesByFilter(owner, List.of(1L, 2L), null);

        // Assert
        assertThat(result).hasSize(1);
    }

    @Test
    void getRecipesByFilter_ShouldFilterByFoodType_WhenProvided() {
        // Arrange
        when(recipeRepository.findByOwnerIdAndIngredientIdsAndFoodType(1L, List.of(1L), "RICE"))
                .thenReturn(List.of(recipe));

        // Act
        List<RecipeResponseDto> result = recipeService.getRecipesByFilter(owner, List.of(1L), FoodType.RICE);

        // Assert
        assertThat(result).hasSize(1);
    }
}
