package dev.fmhj97.whatdoicookbackend.service;

import dev.fmhj97.whatdoicookbackend.dto.recipe.RecipeCreateDto;
import dev.fmhj97.whatdoicookbackend.dto.recipe.RecipeResponseDto;
import dev.fmhj97.whatdoicookbackend.dto.recipe.RecipeUpdateDto;
import dev.fmhj97.whatdoicookbackend.entity.Recipe;
import dev.fmhj97.whatdoicookbackend.entity.User;
import dev.fmhj97.whatdoicookbackend.entity.enums.FoodType;
import dev.fmhj97.whatdoicookbackend.entity.enums.Source;
import dev.fmhj97.whatdoicookbackend.exception.DuplicateResourceException;
import dev.fmhj97.whatdoicookbackend.exception.ForbiddenException;
import dev.fmhj97.whatdoicookbackend.exception.ResourceNotFoundException;
import dev.fmhj97.whatdoicookbackend.repository.RecipeRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class RecipeService {

    private final RecipeRepository recipeRepository;

    /**
     * Constructor.
     * @param recipeRepository
     */
    public RecipeService(RecipeRepository recipeRepository) {
        this.recipeRepository = recipeRepository;
    }

    /**
     * Returns a single recipe by the given ID (owned by the current user).
     * @param id The recipe ID.
     * @param currentUser The current user.
     * @return The recipe data.
     */
    public RecipeResponseDto getRecipeById(Long id, User currentUser) {
        Recipe recipe = recipeRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Recipe not found with id: " + id));

        // Checks if the owner of the recipe is the same as the current user.
        if (!recipe.getOwner().getId().equals(currentUser.getId())) {
            throw new ForbiddenException("You do not have permission to access this recipe");
        }

        return RecipeResponseDto.from(recipe);
    }

    /**
     * Returns a list of all recipes owned by the current user.
     * If a title and/or foodType are provided, filters by them.
     * @param currentUser The current user.
     * @param title Optional filter by recipe title.
     * @param foodType Optional filter by recipe foodType.
     * @return List of recipes.
     */
    public List<RecipeResponseDto> getMyRecipes(User currentUser, String title, FoodType foodType) {

        boolean hasTitle = title != null && !title.isBlank();
        boolean hasFoodType = foodType != null;

        if (hasTitle && hasFoodType) {
            return recipeRepository.findByOwnerIdAndTitleContainingIgnoreCaseAndFoodType(
                    currentUser.getId(), title, foodType).stream()
                    .map(RecipeResponseDto::from)
                    .toList();
        }
        else if (hasTitle) {
            return recipeRepository.findByOwnerIdAndTitleContainingIgnoreCase(
                    currentUser.getId(), title).stream()
                    .map(RecipeResponseDto::from)
                    .toList();
        }
        else if (hasFoodType) {
            return recipeRepository.findByOwnerIdAndFoodType(currentUser.getId(), foodType).stream()
                    .map(RecipeResponseDto::from)
                    .toList();
        }
        else {
            return recipeRepository.findByOwnerId(currentUser.getId()).stream()
                    .map(RecipeResponseDto::from)
                    .toList();
        }
    }

    /**
     * Creates a new recipe for the current user, generated by themselves.
     * @param currentUser The current user.
     * @param dto The recipe data.
     * @return The created recipe.
     */
    public RecipeResponseDto createRecipe(User currentUser, RecipeCreateDto dto) {

        if (recipeRepository.existsByOwnerIdAndTitleIgnoreCase(currentUser.getId(), dto.title())) {
            throw new DuplicateResourceException("Recipe already exists with title: " + dto.title());
        }

        Recipe newRecipe = new Recipe(
                dto.title(),
                currentUser,
                dto.description(),
                dto.foodType(),
                Source.USER,
                dto.servings(),
                dto.prepTimeMin(),
                dto.cookTimeMin()
        );

        return RecipeResponseDto.from(recipeRepository.save(newRecipe));
    }

    /**
     * Deletes a recipe by the given ID (owned by the current user).
     * @param currentUser The current user.
     * @param id The recipe ID.
     */
    public void deleteRecipe(User currentUser, Long id) {

        Recipe recipe = recipeRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Recipe not found with id: " + id));

        if (!recipe.getOwner().getId().equals(currentUser.getId())) {
            throw new ForbiddenException("You do not have permission to delete this recipe");
        }

        recipeRepository.deleteById(id);
    }

    /**
     * Updates an existing recipe by the given ID (owned by the current user).
     * @param currentUser The current user.
     * @param id The recipe ID.
     * @param dto The updated data.
     * @return The updated recipe.
     */
    public RecipeResponseDto updateRecipe(User currentUser, Long id, RecipeUpdateDto dto) {

        Recipe recipe = recipeRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Recipe not found with id: " + id));

        if (!recipe.getOwner().getId().equals(currentUser.getId())) {
            throw new ForbiddenException("You do not have permission to update this recipe");
        }

        if (dto.title() != null && !dto.title().isBlank()) {

            if (recipeRepository.existsByOwnerIdAndTitleIgnoreCase(currentUser.getId(), dto.title())
                    && !recipe.getTitle().equalsIgnoreCase(dto.title())) {
                throw new DuplicateResourceException("Recipe already exists with title: " + dto.title());
            }

            recipe.setTitle(dto.title());
        }

        if (dto.description() != null && !dto.description().isBlank()) recipe.setDescription(dto.description());

        if (dto.foodType() != null) recipe.setFoodType(dto.foodType());

        if (dto.servings() != null) recipe.setServings(dto.servings());

        if (dto.prepTimeMin() != null) recipe.setPrepTimeMin(dto.prepTimeMin());

        if (dto.cookTimeMin() != null) recipe.setCookTimeMin(dto.cookTimeMin());

        return RecipeResponseDto.from(recipeRepository.save(recipe));
    }
}
